export default [
  { path: '/', component: '@/pages/index', title: 'Flexible Employment Home'},
  { path: '/login', component: '@/pages/login', title: 'Flexible Employment Login'},
  // { path: '/personal-form', component: '@/pages/personalForm', title: 'Flexible Employment Information after Login'},
  // { path: '/company-form', component: '@/pages/companyForm', title: 'Flexible Employment Company Information'},
  // { path: '/perfect-label', component: '@/pages/perfectLabel', title: 'Flexible Employment'},
  // { path: '/choose-role', component: '@/pages/chooseRole', title: 'Flexible Employment'},
  // { path: '/my-page', component: '@/pages/myPage', title: 'Flexible Employment Home'},
  // { path: '/appraise/:id', component: '@/pages/appraise', title: 'Flexible Employment Publish Evaluation'},
  // { path: '/chat/:id', component: '@/pages/chat', title: 'Flexible Employment Chat Consultation'},
  // { path: '/chat-list', component: '@/pages/chatList', title: 'Flexible Employment Message List'},
  // { path: '/collection', component: '@/pages/collection', title: 'Flexible Employment My Collection'},
  // { path: '/date-point/:rsd_state/rsd/:rsd_id/sd/:sd_id/sdl/:sdl_id', component: '@/pages/datePoint', title: 'Flexible Employment Interview Operation'},
  // { path: '/demand/:id', component: '@/pages/demand', title: 'Flexible Employment Demand Details'},
  // { path: '/demand-order-list/:order_state?', component: '@/pages/demandOrderList', title: 'Flexible Employment My Orders'},
  // { path: '/demand-create/:direction/:id', component: '@/pages/demandCreate', title: 'Flexible Employment Publish Demand'},
  // { path: '/demand-create', component: '@/pages/demandCreate', title: 'Flexible Employment Publish Demand'},
  // { path: '/forgot-password', component: '@/pages/forgotPassword', title: 'Flexible Employment Forgot Password'},
  // { path: '/job/:id', component: '@/pages/job', title: 'Flexible Employment Job Details'},
  // { path: '/job-order/:sd_id/rsd/:rsd_id', component: '@/pages/jobOrder', title: 'Flexible Employment My Application Details'},
  // { path: '/job-order-list/:rsd_state?', component: '@/pages/jobOrderList', title: 'Flexible Employment My Applications'},
  // { path: '/like/:rsd_id', component: '@/pages/like', title: 'Flexible Employment Evaluation'},
  // { path: '/location/:sd_id/:sdl?/:sdl_id?', component: '@/pages/location', title: 'Flexible Employment Demand Information'},
  // { path: '/location-list/:sd_id', component: '@/pages/locationList', title: 'Flexible Employment Demand List'},
  // { path: '/msg/:id', component: '@/pages/msg', title: 'Flexible Employment System Information'},
  // { path: '/my-job/:id/sdl/:sdl_id/:state?/:rsd_state?', component: '@/pages/myJob', title: 'Flexible Employment My Job Details'},
  // { path: '/offer/:id', component: '@/pages/offer', title: 'Flexible Employment Offer Details'},
  // { path: '/offer-list', component: '@/pages/offerList', title: 'Flexible Employment My Offers'},
  // { path: '/offer-view/:id', component: '@/pages/offerView', title: 'Flexible Employment Demand Order Details'},
  // { path: '/order-details/:id', component: '@/pages/orderDetails', title: 'Flexible Employment Order Details'},
  // { path: '/pay-response/:price/number/:number/way/:way/:sd?/:sd_id?', component: '@/pages/payResponse', title: 'Flexible Employment Payment Status'},
  // { path: '/profile/:userId?/:direction?/:itemId?', component: '@/pages/profile', title: 'Flexible Employment Profile'},
  // { path: '/register', component: '@/pages/register', title: 'Flexible Employment Register'},
  // { path: '/resume', component: '@/pages/resume', title: 'Flexible Employment Resume Information'},
  // { path: '/search/:type?/:value?', component: '@/pages/search', title: 'Flexible Employment Search'},
  // { path: '/service/:id', component: '@/pages/service', title: 'Flexible Employment Service Details'},
  // { path: '/service-create/:id', component: '@/pages/serviceCreate', title: 'Flexible Employment Publish Service'},
  // { path: '/service-create', component: '@/pages/serviceCreate', title: 'Flexible Employment Publish Service'},
  // { path: '/service-order-list/:order_state?', component: '@/pages/serviceOrderList', title: 'Flexible Employment My Orders'},
  // { path: '/user-agreement/:target?', component: '@/pages/userAgreement', title: 'Flexible Employment Platform Service Agreement'},
  // { path: '/wechat-start', component: '@/pages/wechatStart', title: 'Flexible Employment'},
  // { path: '/work-history/:id?', component: '@/pages/workHistory', title: 'Flexible Employment Work History'},
  // { path: '/employee/:member_id/rsd_sdl/:rsd_sdl_id/rsd/:rsd_id/sd/:sd_id', component: '@/pages/employee', title: 'Flexible Employment Employer View Resume'},
];